src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateEmailForProjectOwnersTest.cls
@isTest
private class CreateEmailForProjectOwnersTest {
    public static String CRON_EXP = '0 0 22 ? * *';
    
    
    static testMethod void testScheduledJob(){
        List<Project__c> proj = new List<Project__c>();
        List<Test_Case__c> TC = new List<Test_Case__c>();
        
        for(Integer i=0; i<4; i++){
            Project__c p = new Project__c(
                Name = 'ProjectTest' + i,
                Status__c = 'Ongoing'
            );
            proj.add(p);           
        }
        insert proj;
        
        for (Project__c p : proj){
            for(Integer i=0; i<2; i++){
                Test_Case__c t = new Test_Case__c(
                    Title__c = 'TestCase ' + p.Name + ' - ' + i,
                    Project__c = p.Id
                );
                TC.add(t);	                
            }
        }
        insert TC;
        
        
        Map<Id, Project__c> projMap = new Map<Id, Project__c>(proj);
        List<Id> projIds = new List<Id>(projMap.keySet());
        Test.startTest();
        
        String jobId = System.schedule('ScheduledApexTest', CRON_EXP, new CreateEmailForProjectOwners());
        
        System.debug('**********');
        
        System.assert(TC.size() >0);
 	 }
}