src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RetriveRelatedTestCaseTest.cls
@isTest
public class RetriveRelatedTestCaseTest {

	@isTest	    
    static void getRelatedTestCases() 
	{				
		Project__c proj = new Project__c();
        proj.Name = 'TestProject';
        proj.Status__c = 'Ongoing';        
		Test_Case__c testCase = new Test_Case__c();
        insert proj;
        testCase.Project__c = proj.Id;
        testCase.Description__c = 'Description for Test unit';
        insert testCase;
                
        List <Test_Case__c> testCases = RetriveRelatedTestCase.getRelatedTestCases(proj.Id);                   
        Test_Case__c TC = testCases.get(0);            
        System.assert(TC.Id == testCase.Id);
	}
    
    @isTest	    
    static void	 deleteTestCase() 
	{				
		Project__c proj = new Project__c();
        proj.Name = 'TestProject';
        proj.Status__c = 'Proposed';
        insert proj;
		Test_Case__c testCase = new Test_Case__c();
        testCase.Project__c = proj.Id;
        testCase.Description__c = 'Description for Test unit';
        insert testCase;
                
        Test_Case__c testC = RetriveRelatedTestCase.deleteTestCase(testCase);        
        List <Test_Case__c> testCases = RetriveRelatedTestCase.getRelatedTestCases(proj.Id);
		                  
        System.assert(testCases.IsEmpty());        
	}
    
}