src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case_Step__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Test_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Case</label>
        <referenceTo>Test_Case__c</referenceTo>
        <relationshipLabel>Test Cases Steps</relationshipLabel>
        <relationshipName>Test_Cases_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Case Step</label>
    <nameField>
        <displayFormat>TS-{0000000000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RetreiveRelatedStepsTest.cls
@isTest
public class RetreiveRelatedStepsTest {
    
    @isTest	    
    static void GetRelatedSteps() 
    {				
        Project__c proj = new Project__c();
        proj.Name = 'TestProject';
        proj.Status__c = 'Ongoing';        
        Test_Case__c testCase = new Test_Case__c();
        insert proj;
        testCase.Project__c = proj.Id;
        testCase.Description__c = 'Description for Test unit';
        insert testCase;
        Test_Case_Step__c step = new Test_Case_Step__c();
        step.Description__c = 'TestDescription';
        step.Test_Case__c = testCase.Id;
        insert step;
                                            
        List <Test_Case_Step__c> steps = RetreiveRelatedSteps.GetRelatedSteps(testCase.Id);                
        Test_Case_Step__c stp = steps.get(0);                
        System.assert(stp.Id == step.Id);
    }
    
}