src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RetreiveProjectsTest.cls
@isTest
public class RetreiveProjectsTest {
    
    @isTest	    
    static void getProjects() 
    {				
        List<Project__c> projects = new List<Project__c>();
                                
        for(Integer i=3; i>0;i--){
            Project__c proj = new Project__c();
            if(i != 1){            
            proj.Name = 'TestProject'+i;
        	proj.Status__c = 'Ongoing'; 
            }else{
                proj.Status__c = 'Finished'; 
            }
            projects.add(proj);
        }
        insert projects;
		
        List <Project__c> projects2 = RetreiveProjects.getProjects();		
        System.debug('*******' + projects2);
        
        System.assert(projects2.size() == 2);
    }
    
}