src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateEmailForProjectOwners.cls
global class CreateEmailForProjectOwners implements Schedulable {
    
    global void execute (SchedulableContext SC){       
        SendEmailToProjectOwner();      
        // CreateEmailForProjectOwners sendDailyEmail = new CreateEmailForProjectOwners();
        // string sch = '0 0 22 ? * *';        
        // System.schedule('Send Daily Email', sch, sendDailyEmail);	
    }
    
    global void SendEmailToProjectOwner()
    {
        
        list <Project__c> projects = [SELECT Id, Name, Status__c, ownerId, owner.email, (SELECT Id FROM Test_Cases__r)
                                      FROM Project__c WHERE Status__c = 'Ongoing'];
        
        List<AggregateResult> ownerId = [SELECT OwnerId, owner.email FROM Project__c WHERE Status__c = 'Ongoing' GROUP BY OwnerId, owner.email];
        
        List<Messaging.SingleEmailMessage> mails =  new List<Messaging.SingleEmailMessage>();        
        
        for(AggregateResult oId : ownerId){
            
            Messaging.SingleEmailMessage mail =  new Messaging.SingleEmailMessage();
            
            List<String> sendTo = new List<String>();        
            string mailAddress =  String.valueof(oId.get('email'));                
            sendTo.add(mailAddress);
            mail.setToAddresses(sendTo);
            
            mail.setSubject('List of Ongoing Projects');
            String email = 'Estimado/a, ' + '<br/> <br/>' +
                'Estos son los proyectos con estado Ongoing al dia de hoy: <br/><br/>';
            
            for(Project__c p : projects)
            {
                if(p.ownerId == oId.get('OwnerId')){                                                                                       
                    email += 'Nombre: ' + p.Name + ' Status: ' + p.Status__c + 'Test Cases: ' + p.Test_Cases__r.size() + '<br/>';                                                                                 
                }                 
            }
            email += '<br/> Saludos.<br/><br/>';
            mail.setHtmlBody(email);                  
        }
        if(mails.size()>0)	Messaging.sendEmail(mails);            
    }
}