src/objects/Test_Case__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case_Step__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <label>Expected Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Test_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Case</label>
        <referenceTo>Test_Case__c</referenceTo>
        <relationshipLabel>Test Cases Steps</relationshipLabel>
        <relationshipName>Test_Cases_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Case Step</label>
    <nameField>
        <displayFormat>TS-{0000000000}</displayFormat>
        <label>Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RetreiveRelatedSteps.cls
public class RetreiveRelatedSteps {
	    @AuraEnabled
    public static List<Test_Case_Step__c> GetRelatedSteps(string testCaseId){       
		RETURN [SELECT Description__c, Index__c, Expected_Result__c,Id,Name, Test_Case__r.Id FROM Test_Case_Step__c
                WHERE Test_Case__r.Id =: testCaseId ORDER BY Index__c];      
       /* return [SELECT Description__c,Expected_Result__c,Id,Name, Test_Case__r.Id FROM Test_Case_Step__c
                WHERE Test_Case__r.Id =: testCaseId];               */
    }
    
     @AuraEnabled
    public static void SetIndexInStep(List<Test_Case_Step__c> stepList){
        List<Test_Case_Step__c> auxLst = new List<Test_Case_Step__c>();
        Integer indx = 0;
        for(Test_Case_Step__c stp: stepList){
            stp.Index__c = indx;
            auxLst.add(stp);
            indx++;
        }
        update auxLst;
    }
}